config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:create, :new]
  resources :cats
  resources :cat_rental_requests, only: [:index, :create, :destroy, :update, :new, :edit, :show, :approve, :deny]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  GENDERS = ['M', 'F']
  CAT_COLORS = [ '',
             'Black',
             'White',
             'Calico',
             'Brown Tabby',
             'Orange Tabby',
             'Grey',
             'Blue',
             'Other']

  validates :birth_date, :color, :name, :sex, presence: true

  validates :sex, inclusion: { in: GENDERS, message: "%{value} is not a valid gender" }

  validates :color, inclusion: { in: CAT_COLORS, message: "%{value} is not a valid color"}

  has_many :rental_requests,
    class_name: "CatRentalRequest",
    dependent: :destroy

  def age
    now = DateTime.now.to_date
    age = now.year  - birth_date.year
    if (now.month == birth_date.month && now.day >= birth_date.day) ||
        now.month > birth_date.month
        age += 1
    end
    age
    # time_ago_in_words(birth_date)
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = %w(APPROVED DENIED PENDING)

  after_initialize :set_status
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUSES, message: "Invalid Status" }
  validate  :approved_request_cannot_overlap_with_any_approved_request
  validate  :start_date_is_before_end_date

  belongs_to :cat, dependent: :destroy

  def approve!
    raise "not pending" unless self.status == "PENDING"
    transaction do
      self.update(status: "APPROVED")
      overlapping_pending_requests.update_all(status: 'DENIED' )
    end
  end

  def approved?
    self.status == "APPROVED"
  end

  def denied?
    self.status == "DENIED"
  end

  def deny!
    self.update(status: "DENIED")
  end

  def pending?
    self.status == "PENDING"
  end

  private
  def set_status
    self.status ||= "PENDING"
  end

  def overlapping_requests
    CatRentalRequest
        .where.not(id: self.id)
        .where(cat_id: cat_id)
        .where(<<-SQL, start_date: start_date, end_date: end_date)
            NOT((start_date > :end_date) OR (end_date < :start_date))
        SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def approved_request_cannot_overlap_with_any_approved_request
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:dates] << "cannot overlap with existing approved requests"
    end
  end

  def start_date_is_before_end_date
    if end_date < start_date
      errors[:start_date] << "cannot be after end date"
      errors[:end_date] << "cannot be before start date"
    end
  end

  def greedy_interval_scheduling
  
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token!

  validates :password_digest, presence: true

  validates :password, length: {minimum: 6, allow_nil: true}
  validates :session_token, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  has_many :cats
  
  attr_accessor :password
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  private
  def require_no_user!
    redirect_to cats_url unless current_user.nil?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @requests = CatRentalRequest.all
    render :index
  end

  def new
    @request = CatRentalRequest.new
    @cats = Cat.all

    render :new
  end

  def create
    @request = CatRentalRequest.new(request_params)
    @cats = Cat.all

    if @request.save
      redirect_to cat_rental_requests_url
    else
      render :new
    end
  end

  def edit
    @request = CatRentalRequest.new
    @cats = Cat.all

    render :edit
  end

  def update
    @request = CatRentalRequest.find(params[:id])

    if @request.update(request_params)
      redirect_to cat_rental_request(@request)
    else
      render :edit
    end
  end

  private
  def request_params
    params.require(:requests).permit(:start_date, :end_date, :cat_id)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_ownership, only: [:update, :edit]
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.owner_id = current_user.id

    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def destroy
    cat = Cat.find(params[:id])
    cat.destroy

    redirect_to cats_url
  end

  private
  def ensure_ownership(cat)
    if cat.owner_id != current_user.id
      render :index 
    end
  end

  def cat_params
    params.require(:cats).permit(:name, :birth_date, :sex, :color, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_user!, only: [:create, :new]
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login_user!(@user)
      redirect_to cats_url
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_user!
  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      msg = UserMailer.welcome_email(@user)
      msg.deliver
      redirect_to cats_url
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @user = User.new
  end


  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate_action
    <<-HTML.html_safe
      <input type="hidden"
            name="authenticity_token"
            value="#{form_authenticity_token}">
    HTML
  end

  def method_action(method)
    <<-HTML.html_safe
      <input type="hidden" name="_method" value="#{method}">
    HTML
  end

end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cat_rental_requests/_form.html.erb
<% action_url =   @request.persisted? ? cat_rental_request_url(@cat) : cat_rental_requests_url %>
<% method =       @request.persisted? ? "PATCH" : "POST" %>
<% submit_text =  @request.persisted? ? "Update Request" : "Submit Request" %>
<%= @request.errors.full_messages.empty? ? "" : @request.errors.full_messages %>
<br>

<form action="<%= action_url %>" method="post">
  <%= authenticate_action %>
  <%= method_action(method) %>
  <label for="requests_cat_id">Select a cat:</label>
  <select name="requests[cat_id]" id="requests_cat_id">
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label for="requests_start_date">Start Date:</label>
  <input
    type="date"
    name="requests[start_date]"
    id="requests_start_date"
    value="<%= @request.start_date %>">

    <br>

  <label for="requests_end_date">End Date:</label>
  <input
    type="date"
    name="requests[end_date]"
    id="requests_end_date"
    value="<%= @request.end_date %>">

  <br>

  <button type="submit"><%= submit_text %></button>
</form>

app/views/cat_rental_requests/index.html.erb
<h1>All Cat Rental Requests</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Cat ID</th>
  </tr>
  <% @requests.each do |request| %>
  <tr>
    <td><%= request.id %></td>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.cat_id %></td>
  </tr>
  <% end %>
</table>

<a href="<%= new_cat_rental_request_url %>">Create a new request</a>

app/views/cat_rental_requests/new.html.erb
<h1>Request a cat rental!</h1>

<%= render "form" %>

app/views/cats/_form.html.erb
<% action_url =   @cat.persisted? ? cat_url(@cat) : cats_url %>
<% method =       @cat.persisted? ? "PATCH" : "POST" %>
<% submit_text =  @cat.persisted? ? "Update Cat!" : "Create Cat!" %>

<form action="<%= action_url %>" method="post">
  <%= authenticate_action %>
  <%= method_action(method) %>

  <label for="cats_name">Name:</label>
  <input
    type="text"
    name="cats[name]"
    id="cats_name"
    value="<%= @cat.name %>">

  <br>

  <span>Sex:</span>
  <label for="cats_sex_m">M</label>
  <input
    type="radio"
    name="cats[sex]"
    id="cats_sex_m"
    value="M"
    checked>
  <label for="cats_sex_m">F</label>
  <input
    type="radio"
    name="cats[sex]"
    id="cats_sex_f"
    value="F">

  <br>

  <label for="cats_color">Color:</label>
  <select name="cats[color]" id="cats_color">
    <% Cat::CAT_COLORS.each do |color| %>
      <option "<% if @cat.color == color %> selected <% end %>">
        <%= color %>
      </option>
    <% end %>
  </select>

  <br>

  <label for="cats_birth_date">Date of Birth:</label>
  <input
    type="date"
    name="cats[birth_date]"
    id="cats_birth_date"
    value="<%= @cat.birth_date %>">

  <br>

  <label for="cats_description">Description:</label>
  <textarea name="cats[description]" id="cats_description"><%= @cat.description %></textarea>

  <br>

  <button type="Submit" name="Submit"><%= submit_text %></button>
</form>

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %></h1>

<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1>Here Are All Our Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <a href="<%= cat_url(cat.id) %>">
        <%= cat.name %>
      </a>
    </li>
  <% end %>
</ul>

<a href="<%= new_cat_url %>">Add a New Cat!</a>
<br>
<a href="<%= cat_rental_requests_url %>">Go to Cat Rentals</a>

app/views/cats/new.html.erb
<h1>Add a new Cat!</h1>

<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>


<h3>Rental Requests</h3>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>
      Approve
    </th>
  </tr>
  <% @cat.rental_requests.order('start_date').each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
  </tr>
  <% end %>
</table>

<br>
<a href="<%= edit_cat_url(@cat) %>">Edit Cat Details</a>
<br>
<a href="<%= cats_url %>">Return to All Cats</a>
<br>
<br>
<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <button type="submit">Delete Cat</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNinecats</title>
</head>
<body>
  <% if logged_in? %>
  <h1>Welcome, <%= current_user.username %></h1>
  <%= button_to "Logout", session_url, method: :delete  %>
  <% else %>
  <%= link_to "Sign in", new_session_url %>
  <%= link_to "Sign up", new_user_url %>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>
<form action="<%= users_url %>" method="post">
  <div class="profile-login"></div>
  <%= authenticate_action %>
 <label for="username">Username:</label>
 <input id="username" name="user[username]" type="text"><br>
 <label for="email">Email:</label>
 <input type="email" id="email" name="user[email]"> <br>
 <label for="password">Password:</label>
  <input id="password" name="user[password]" type="password" ><br>
  <input type="submit" value="Submit"><br>
</form>
</div>